---
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq s3cmd
script: bundle exec rake checkout_ember build
after_success: bundle exec rake versions:deploy_edge
env:
  global:
  - S3_ACCESS_KEY_ID: "XU+jCNlR0HFaf7wlc4uQcGtox3KyzxLeIVokYsHwmeakxIXeAqjPEoDlI/RW\n8exV02rK3vIoVh0IXoW/3SwknKrMEoYyMq4cfudrtUOdLI4/SdOftAieeHzq\nx7FSb+UFH4ZvN17vshLpGMdNfYCFLdeViiFuW5VhVe2kaawvX7M="
  - S3_SECRET_ACCESS_KEY: "cPnptQbRgE7LiBE9CRxX9vqT67Dhe1GhYe5/JuvcxrenS78m4xN4Y8vymHQP\nds2MtuPViydBI7GJlwPXmZcKwuKcJgs0F7um05OjQ3eyCy0ViPVSFypBpOjC\n2AQQja7JhrYnwfaLk1c7gyrnWrCb6yrCdMHygvQjqSbUr/in1b0="

